### ISSUE TITLE
[Bug] Command to fill in with water, air pockets left by aquatic plants after removing and re-adding Zawa

### ISSUE THREAD

**Issue by KnightCa** [gkazan/ZAWA#213]
**Describe the bug**
After removing Zawa & Bookworm and then adding it back to a server, the aquatic plants in explored chunks have been replaced with Air. A command is needed to replace these Air squares with water on the sea floor.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Explore several chunks of aquatic area with Zawa plant life.
2. Remove Zawa and Bookworm from server (to test lag source)
3. Re-access Minecraft and look in the aquatic areas explored. Aquatic plant locations have been replaced with Air.
4. Re-add Zawa and Bookworm to server (and really wish that I had made a backup of Server before doing this).

**Expected behavior**
I did not realize at first that Zawa was the source of the aquatic plants. After re-adding it back to the server, I had hoped there would be a way to replace these air pockets with water or aquatic plants in chunks.

Using the fill command doesn't work well, since we only want this to impact the aquatic ocean floor. The fill command impacts nearby caves and such outside of the ocean floor.

**Please complete the following information):**
 - Mod Version Number : 2.1.3
 - Bookworm Version Number : 2.5.2.1
 - Forge Version Number : 1.12.2
 - Are other mods installed? :  No
 - Is OptiFine installed? :  No
 - Is this bug present in single player or on a server or both? : I assume it happens in both, although only tested on Server

**Comment by gkazan** [comment]
This is not a bug and should be expected when removing mods.
